name: Continuous Integration

on: push

jobs:
  test-release:
    name: Test release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          key: npm-${{ hashFiles(format('{0}{1}', github.workspace,
            '/package-lock.json')) }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --prefer-offline --progress=false
      - name: Release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_HEAD_REF: $GITHUB_HEAD_REF
        run: npx semantic-release --dry-run --debug -b $GITHUB_HEAD_REF
