name: Release to NPM

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release to NPM and github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: perform clean install
        run: npm ci --unsafe-perm
      - env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
